### ISSUE TITLE
[RPI3] install on Archlinux-ARM

### ISSUE THREAD

**Issue by semeion** [rpicoin/rpicore#4]
Could be nice have instruction about how to build/install in Archlinux-ARM.

The Wiki page isn´t working.

**Comment by TUXCMD** [comment]
> Could be nice have instruction about how to build/install in Archlinux-ARM.
> 
> The Wiki page isn´t working.

We are currently working on the new FAQ / WIKI Section 

- including:

1. Installation guide for the wallets (Different Operating Systems);
2. Wallet specific information about the functions and such;
3. The information and installation guide for the MasterNodes and The Regular staking process;

I'll make sure to follup up on this request and close the issue as soon as we have delivered the required information on our new WiKi / FAQ Web section!

**Comment by semeion** [comment]
Nice, a CLI wallet is important, my rpi3 run full time (online the hole year) and don´t have GUI. Could be nice have rpicore on it.

**Comment by TUXCMD** [comment]
> Nice, a CLI wallet is important, my rpi3 run full time (online the hole year) and don´t have GUI. Could be nice have rpicore on it

The v040 wallets will be released today or tomorrow, these are compiled (or builded) with our Gitian server and comes with properly signed packages / installers. 

### That means that the following will be available in the new release:

- rpicoind (headless deamon / which doesn't accept any RPC requests anymore).
- rpicoin-cli (the command-line as available within the GUI version)
- rpicoin-tx
- test_rpicoin_qt
- test_rpicoin
for example: ./rpicoin-cli getinfo or ./rpicoin-cli stop (to stop the daemon from running).

**WINDOWS**
- Windows installer
- Windows 32bits & 64bits binaries

**LINUX**
- aarch64
**- arm (Raspberry Pi or Other ARM based kernels)**
- i686-pc
- riscv64
- x86_x64 (Ubuntu / Debian etc..)

**MacOS / OSX**
- This will be a .dmg file that needs to be placed in the ~/Applications/ directory of your OS.
(More information about this build, will be there soon).

@semeion 
As soon as the new release is available on Github - I will make sure to notify you about that! 


Cheers!

**Comment by semeion** [comment]
Great news, very nice. I will try use it for use, but it is important provide some info about how to compile to armv7l, armv7h, ..., because my rpi3b is using Archlinux-ARM to armv7 (32 bits). I am not sure if it run on 32 bits OS version.

**Comment by TUXCMD** [comment]
> Great news, very nice. I will try use it for use, but it is important provide some info about how to compile to armv7l, armv7h, ..., because my rpi3b is using Archlinux-ARM to armv7 (32 bits). I am not sure if it run on 32 bits OS version.

We have recently published our new v0.4.0 wallets, we have the binaries for the Raspberry Pi which you can download directly from Github

**Instructions**
You can try the following from the terminal on your raspberry pi

`sudo apt-get update && sudo apt-get upgrade`
`sudo apt-get install git`

(It migt be necessary to create a swapfile / partition depending on if you wish to use the GUI version or just the daemon)

Now download RPICoin version 0.4.0 (latest). When released, newer versions can be found at [github.com/rpicoin/rpicore/releases ](url)

**Raspbery Pi uses arm-linux-gnueabihf file for 32 bit. Command below:**

`wget https://github.com/rpicoin/rpicore/releases/download/v0.4.0/rpicoin-0.4.0-arm-linux-gnueabihf.tar.gz`

` tar -xvzf rpicoin-0.4.0-arm-linux-gnueabihf.tar.gz --strip 2`

`mkdir ~/.rpicoin`

`nano ~/.rpicoin/rpicoin.conf`
_Here add the following:_

```
rpcuser=ahardtoguessrandomusername
rpcpassword=hard-long-very-longhjo4002nfchar-password
rpcallowip=127.0.0.1
addnode=seed1.rpicoin.com
addnode=seed2.rpicoin.com
addnode=explorer.rpicoin.com
maxconnections=32
```

**Try launching the rpicoind (daemon) and see if this parses any error in the console:**
`./rpicoin-0-4-0/bin/rpicoind -daemon`

`./rpicoin-0.4.0/bin/rpicoin-cli getinfo`
Checks the synchronization status and provides other info about current staking status. and block height.

If that works you can try launching the QT (GUI) version of the wallet with the following command:

`cd ~/rpicoin-0.4.0/bin/`

`./rpicoin-qt`

Let me know the outcome of this, otherwise we'll have to cross-compile the build!

**Comment by semeion** [comment]
Oh great news! Thanks for reply! 
The above instructions teach how to install pre-compiled image right?

Archlinux-ARM have the AUR to build that kind of package. Using the AUR the user build from source using a single PKGBUILD file and make a system wide installation with dependencies control.

I will check the sources and try create a PKGBUILD file to build it locally and publish on AUR. On this way everybody using Archlinux could build and install the package using a single command. I have no time right now, but i will try it later.

**Comment by TUXCMD** [comment]
I will close this issue as I assume it's resolved, if you need any further help you can re-open a issue! Thanks.
